language: python

python:
  - "3.5"

install:
  - pip install -q tox flake8 coverage coveralls
  - python setup.py install

before_script:
  - make flake8

script:
  - tox

after_success:
  - make coveralls

