language: python

matrix:
  include:
    - { python: "2.7", env: TOXENV=py27-dj111 }

    - { python: "3.4", env: TOXENV=py34-dj111 }

    - { python: "3.5", env: TOXENV=py35-dj111 }
    - { python: "3.5", env: TOXENV=py35-dj22  }

    - { python: "3.6", env: TOXENV=py36-dj111 }
    - { python: "3.6", env: TOXENV=py36-dj22  }
    - { python: "3.6", env: TOXENV=py36-dj30  }

    - { python: "3.7", dist: xenial, env: TOXENV=py37-dj111 }
    - { python: "3.7", dist: xenial, env: TOXENV=py37-dj22  }
    - { python: "3.7", dist: xenial, env: TOXENV=py37-dj30  }

    - { python: "3.8", dist: xenial, env: TOXENV=py38-dj111 }
    - { python: "3.8", dist: xenial, env: TOXENV=py38-dj22  }
    - { python: "3.8", dist: xenial, env: TOXENV=py38-dj30  }

install:
  - pip install -q tox coveralls

script:
  - tox

after_success:
  - coveralls
