language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"


env:
  - DJANGO=django==1.4.19
  - DJANGO=django==1.5.12
  - DJANGO=django==1.6.11
  - DJANGO=django==1.7.7
  - DJANGO=django==1.8


matrix:
  exclude:
    - python: "2.6"
      env: DJANGO=django==1.7.7
    - python: "2.6"
      env: DJANGO=django==1.8
    - python: "3.3"
      env: DJANGO=django==1.4.18
    - python: "3.4"
      env: DJANGO=django==1.4.18


install:
  - pip install -q $DJANGO
  - pip install -q flake8 coverage coveralls
  - python setup.py install

before_script:
  - make flake8

script:
  - make coverage

after_success:
  - make coveralls

