language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"


env:
  - DJANGO=django==1.4.18
  - DJANGO=django==1.5.13
  - DJANGO=django==1.6.10
  - DJANGO=django==1.7.3


matrix:
  exclude:
    - python: "2.6"
      env: DJANGO=django==1.7
    - python: "3.3"
      env: DJANGO=django==1.4.15
    - python: "3.4":
      env: DJANGO=django==1.4.15


install:
  - pip install -q $DJANGO
  - pip install -q flake8
  - python setup.py install

before_script:
  - make flake8

script:
  - make coverage

after_success:
  - make coveralls

