language: python

python:
  - "2.6"
  - "2.7"
  - "3.3"
  - "3.4"

env:
  - DJANGO=django==1.4.14
  - DJANGO=django==1.5.9
  - DJANGO=django==1.6.6
  - DJANGO="https://www.djangoproject.com/m/releases/1.7/Django-1.7c3.tar.gz"

matrix:
  exclude:
    - python: "2.6"
      env: DJANGO="https://www.djangoproject.com/m/releases/1.7/Django-1.7c3.tar.gz"
    - python: "3.3"
      env: DJANGO=django=1.4.14
    - python: "3.4":
      env: DJANGO=django==1.4.14
install:
  - pip install -q $DJANGO
  - pip install -q flake8
  - python setup.py install

before_script:
  - make flake8

script:
  - make test

after_success:
  - make coveralls
