language: python

matrix:
  include:
    - { python: "3.6", env: TOXENV=py36-dj111 }
    - { python: "3.6", env: TOXENV=py36-dj22  }
    - { python: "3.6", env: TOXENV=py36-dj30  }

    - { python: "3.7", dist: xenial, env: TOXENV=py37-dj111 }
    - { python: "3.7", dist: xenial, env: TOXENV=py37-dj22  }
    - { python: "3.7", dist: xenial, env: TOXENV=py37-dj30  }

    - { python: "3.8", dist: xenial, env: TOXENV=py38-dj111 }
    - { python: "3.8", dist: xenial, env: TOXENV=py38-dj22  }
    - { python: "3.8", dist: xenial, env: TOXENV=py38-dj30  }

    - { python: "3.9", dist: xenial, env: TOXENV=py39-dj22 }
    - { python: "3.9", dist: xenial, env: TOXENV=py39-dj30 }
    - { python: "3.9", dist: xenial, env: TOXENV=py39-dj31 }

install:
  - pip install -q poetry tox tox-travis coveralls

script:
  - tox

after_success:
  - coveralls
